Temporarily reverting some refactoring to resolve undefined reference to `__cxa_pure_virtual' errors.
Still working to resolve the following errors when using OutputBankMODBUS:

OpenTroller\OTOutputModbus.cpp.o:(.rodata._ZTVN11OpenTroller12OutputMODBUSE+0x4): undefined reference to `OpenTroller::OutputMODBUS::getState()'
OpenTroller\OTOutputModbus.cpp.o:(.rodata._ZTVN11OpenTroller12OutputMODBUSE+0xa): undefined reference to `OpenTroller::OutputMODBUS::getName()'
OpenTroller\OTOutputBankModbus.cpp.o: In function `OutputBankMODBUS':
C:\Program Files (x86)\BTArduino-0022\libraries\OpenTroller/OTOutputBankModbus.cpp:29: undefined reference to `vtable for OpenTroller::OutputBankMODBUS'
C:\Program Files (x86)\BTArduino-0022\libraries\OpenTroller/OTOutputBankModbus.cpp:29: undefined reference to `vtable for OpenTroller::OutputBankMODBUS'